environment:
  env: "local" # local, dev, prod
storage:
  db: "sqlite" # mysql, sqlite
  mysql_options:
    mysql_name: "digital-library"
    mysql_user: "root"
    mysql_password: "digital-library"
    mysql_max_conn_lifetime: "3m"
    mysql_max_open_conns: 10
    mysql_max_idle_conns: 10
  sqlite_options:
    sqlite_path: "./.storage/storage.db"
http_server:
  proto: "http"
  host: "localhost"
  port: 5454
  timeout: 20s
  idle_timeout: 40s
